version: '3'
services:
  postgres:
    image: postgres:15.1-alpine
    restart: always
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    container_name: ${DATABASE_HOST}
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
