CREATE TABLE IF NOT EXISTS user_info
(
    user_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(100) NOT NULL,
    surname       VARCHAR(100) NOT NULL,
    password_hash VARCHAR(60)  NOT NULL,
    email         VARCHAR(255) NOT NULL UNIQUE
);

CREATE UNIQUE INDEX IF NOT EXISTS email_user_info_index ON user_info (email);