CREATE TABLE IF NOT EXISTS product
(
    product_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL UNIQUE,
    description TEXT,
    price       FLOAT        NOT NULL,
    amount      INTEGER      NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS product_name_index ON product (name);

CREATE TABLE IF NOT EXISTS category
(
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS product_category
(
    product_category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id         BIGINT REFERENCES category (category_id) ON DELETE CASCADE NOT NULL,
    product_id          BIGINT REFERENCES product (product_id) ON DELETE CASCADE   NOT NULL
);

CREATE INDEX IF NOT EXISTS category_id_product_category_index ON product_category (category_id);